### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by giftmy** [hcwang/openwrt-actions#1]
我无法启动Aria2，是哪里没对

**Comment by hcwang** [comment]
也是小米3Pro吗？我这儿是正常的。
有日志吗？

**Comment by giftmy** [comment]
打开192...:6800
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

**Comment by giftmy** [comment]
> 也是小米3Pro吗？我这儿是正常的。
> 有日志吗？

无法启动

**Comment by giftmy** [comment]
> 也是小米3Pro吗？我这儿是正常的。
> 有日志吗？
Sat Apr 11 11:38:09 2020 daemon.info aria2: Instance "main" disabled.
Sat Apr 11 11:38:41 2020 daemon.err aria2: Please create download dir first.

**Comment by hcwang** [comment]
你应该在下载文件夹中创建一个aria2的子文件夹。
在OpenWrt的Aria2中找到“文件和目录”中找到默认下载目录，看看设置的目录是不是存在？

**Comment by giftmy** [comment]
而且我外置硬盘sda1通过本地电脑也打不开，说我没有访问权限，ShareDisks 在网络共享里面也设置了，允许用户访问，也是没有权限，肯定是哪里没有设置对

**Comment by giftmy** [comment]
外置硬盘在挂载点是可以被发现的，也在文件根目录建立了aria2目录并建立了aria2.config

**Comment by hcwang** [comment]
aria2文件夹的owenr应该是aria2(看你在OpenWrt的Aria2设置中，选择的哪个用户来运行实例，默认是aria2)，所以建议你使用

```
chown -R aria2:aria2 [sda1/aria2]
```

来更新权限，上面命令中中括号的部分请更改为你的aria2真实文件夹路径。

**Comment by giftmy** [comment]
还是不知道什么地方出问题
![Screenshot (2)](https://user-images.githubusercontent.com/44667287/79564590-8bd1c980-80e1-11ea-9a80-340a842b6b3c.png)
![Screenshot (3)](https://user-images.githubusercontent.com/44667287/79564598-8d02f680-80e1-11ea-8478-77bb02cdd0cd.png)
![QQ截图20200417193439](https://user-images.githubusercontent.com/44667287/79565097-8cb72b00-80e2-11ea-9144-e3ed63d4a8ae.png)
![QQ截图20200417193500](https://user-images.githubusercontent.com/44667287/79565101-8f198500-80e2-11ea-83cb-3274064dcc7a.png)
