### ISSUE TITLE
windows下访问外置硬盘

### ISSUE THREAD

**Issue by giftmy** [hcwang/openwrt-actions#2]
没有权限访问，我该怎么做

**Comment by giftmy** [comment]
![QQ截图20200607090553](https://user-images.githubusercontent.com/44667287/83957984-48086e80-a89f-11ea-99ea-c3e94d76098c.png)
![Screenshot](https://user-images.githubusercontent.com/44667287/83957985-4a6ac880-a89f-11ea-9876-565af0044f16.png)

**Comment by hcwang** [comment]
https://aisoa.cn/post-2483.html
