### ISSUE TITLE
安装不起

### ISSUE THREAD

**Issue by giftmy** [hcwang/openwrt-actions#7]
![下载 (1)](https://user-images.githubusercontent.com/44667287/140324039-918c90cb-e83a-431c-9939-e612ca74ea9e.png)
其它的可以正常安装

**Comment by hcwang** [comment]
我昨天刚正常升级，请安装如下镜像：2021-11-04.12.48.bin。由于Image改变了，所以原有的配置无法保留，需要勾选掉“保留配置”。或者使用命令行方式更新如下：

`sysupgrade -n 2021-11-04.12.48.bin`

更新前请先备份所有配置，更新后再恢复备份的配置即可。

**Comment by giftmy** [comment]
明白了

**Comment by giftmy** [comment]
如果在刷2021-11-04之后的bin 需要在勾选保留配置选项吗 ，我的路由器在提出问题后就一直黄灯了，送去修了。

**Comment by hcwang** [comment]
后来发现了一个解决方案，在原配置的/etc/config文件夹中，找到system这个文件，在其中增加一行option compat_version '1.1'，然后就可以勾选保留配置了。

我的刷了之后由黄灯闪烁到亮绿灯似乎也延长了很长时间，好象得三分钟左右，但实际上那时候WIFI已经开始工作了。你可以在WIFI找到OpenWrt的SSID。

`config system
        option hostname 'OpenWrt'
        option ttylogin '0'
        option log_size '64'
        option urandom_seed '0'
        option compat_version '1.1'
        option timezone 'CST-8'
        option zonename 'Asia/Shanghai'
`

**Comment by giftmy** [comment]
还有一个问题shadowsocksr plus+ dns的三种解析模式 切换之后重启 也出现黄灯长亮。

**Comment by hcwang** [comment]
这个你就得去问upstream的开发人员了，我就不清楚了。

**Comment by giftmy** [comment]
辛苦你了一直在维护这个项目，感谢

**Comment by hcwang** [comment]
举手之劳。
